DROP DATABASE one_db;
DROP DATABASE two_db;
CREATE DATABASE one_db;
CREATE DATABASE two_db;
DROP ROLE admin;

CREATE USER admin WITH ENCRYPTED PASSWORD 'root';
ALTER ROLE admin SET client_encoding TO 'utf8';
ALTER ROLE admin SET default_transaction_isolation TO 'read committed';
ALTER ROLE admin SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE one_db TO admin ;
GRANT ALL PRIVILEGES ON DATABASE two_db TO admin ;
